apiVersion: v2
appVersion: 1.18.0
description: A Helm chart for Kubernetes
name: gde-microservice
type: application
version: 0.9.5
dependencies:
  - name: mysql
    version: "15.4.0"
    repository: "https://charts.bitnami.com/postgresql"
    condition: postgress.enabled