serviceName: template-name
init_containers: false
authenticate_requests: false
use_tls: false
service:
  name: template-name
  spec:
    selector:
      app: template-app
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
ingress:
  name: template-ingress
  ## For cert management and nginx, you can define the following annotations
  # annotations:
  #   "cert-manager.io/cluster-issuer": "letsencrypt-issuer"
  #   "nginx.ingress.kubernetes.io/rewrite-target": "/$1"
  annotations: {}
  spec:
    ingressClassName: nginx
    ## Rules can be overwritten as follows ##
    # rules:
    # - host: test-host.com
    #   http:
    #     paths:
    #     - path: /hello-world(/|$)(.*)
    #       pathType: Prefix
    #       backend:
    #         service:
    #           name: hello-world-service
    #           port:
    #             number: 443
    rules: []
    tls: []
    ## tls can be overwritten as follows ##
    # tls:
    # - hosts:
    #   - hello-world-service.replaceme.com
    #   secretName: hello-world-tls
deployment:
  name: template-deployment-name
  spec:
    replicas: 1
    selector:
      ## matchLabels requires a map of key/value pairs
      # matchLabels:
      #   app: template-app
      matchLabels: {}
    template:
      ## containerSpecs should be overwritten like the following
      # containerSpecs:
      # - name: hello-world
      #   image: strongergde/test-repository:latest
      #   ports:
      #   - containerPort: 8080
      containerSpecs: []
      initContainers: []
