service:
  name: template-name
  spec:
    selector:
      app: template-app
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
ingress:
  name: template-ingress
  annotations:
    "cert-manager.io/cluster-issuer": "letsencrypt-issuer"
    "nginx.ingress.kubernetes.io/rewrite-target": "/$1"
  spec:
    ingressClassName: nginx
    rules:
    - host: test-host.com
      http:
        paths:
        - path: /hello-world(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: hello-world-service
              port:
                number: 80
deployment:
  name: template-deployment-name
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: template-app
    template:
      containerSpecs:
      - name: hello-world
        image: k8s.gcr.io/echoserver:1.10
        ports:
        - containerPort: 8080
