apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
{{ toYaml .Values.deployment.selector | indent 4 }}
  template:
    metadata:
      labels:
{{ toYaml .Values.deployment.selector.matchLabels | indent 8 }}
    spec:
      containers:
{{ toYaml .Values.deployment.spec.template.containerSpecs | indent 6 }}
      {{ if .Values.sidecar_authentication }}
      initContainers:
{{ toYaml .Values.deployment.initContainers | indent 6 }}