apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
{{ toYaml .Values.service.spec.selector | indent 4 }}
  ports:
{{ toYaml .Values.service.spec.ports | indent 4}}